# Generated by Django 3.2.18 on 2023-03-23 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campus', '0007_auto_20230320_1936'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='university_slug',
            field=models.SlugField(null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='slug',
            field=models.SlugField(unique=True),
        ),
        migrations.AlterField(
            model_name='university',
            name='slug',
            field=models.SlugField(unique=True),
        ),
    ]
